---
- name: Add Docker signing key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_os_family | lower }}/gpg"
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
      - docker-compose-plugin
    state: latest
    update_cache: yes
  become: yes

- name: Ensure Docker is running
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
